#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                     101
#define IDR_MENU1                       102
#define IDI_APP                         104
#define IDD_SHEET_APP                   201
#define IDD_SHEET_PRC                   202
#define IDD_SHEET_SVC                   203
#define IDD_SHEET_PRF                   204
#define IDD_SHEET_NET                   205
#define IDD_SHEET_USR                   206
#define IDC_TAB_TASK                    1001
#define IDC_LIST_APPLICATIONS           1002
#define IDC_BUTTON_END_TASK             1003
#define IDC_BUTTON_SWITCH_TASK          1004
#define IDC_BUTTON_NEW_TASK             1005
#define IDC_LIST_PROCESSES              1006
#define IDC_BUTTON_END_PRC              1007
#define IDC_CHECKBOX_SPFAU              1008
#define IDC_LIST_SERVICES               1009
#define IDC_LIST_ADAPTER                1010
#define IDC_LIST_USER                   1011
#define IDC_BN_DISCONNECT               1012
#define IDC_BN_QUIT                     1013
#define IDC_BN_SENDMESSAGE              1014
#define IDC_GB_CPU_USAGE                1015
#define IDC_GB_PF_USAGE                 1016
#define IDC_USAGE_BAR_CPU               1017
#define IDC_USAGE_BAR_PF                1018
#define IDC_USAGE_GRAPH_CPU             1019
#define IDC_USAGE_GRAPH_PF              1020
#define IDC_NETWORK_UTILIZATION         1021
#define IDM_NEW                         40001
#define IDM_EXIT                        40002
#define IDM_ALWAYS_ON_TOP               40003
#define IDM_MINIMIZE_ON_USE             40004
#define IDM_HIDE_WHEN_MINIMIZED         40005
#define IDM_REFRESH                     40006
#define IDM_ABOUT                       40007
#define IDM_BKCOLOR                     40008
#define IDM_TEXTCOLOR                   40009
#define IDM_STANDBY                     40010
#define IDM_HIBERNATE                   40011
#define IDM_TURNOFF                     40012
#define IDM_RESTART                     40013
#define IDM_LOGOFF                      40014
#define IDM_SWITCH                      40015

