// The IDL file for IExample2.DLL
//
// {E1124082-5FCD-4a66-82A6-755E4D45A9FC} = Type library's GUID
// {520F4CFD-61C6-4eed-8004-C26D514D3D19} = IExample2 object's GUID
// {B6127C55-AC5F-4ba0-AFF6-7220C95EEF4D} = IExample2 VTable's GUID

[uuid(E1124082-5FCD-4a66-82A6-755E4D45A9FC), version(1.0), helpstring("IExample2 COM server")]
library IExample2
{
    importlib("STDOLE2.TLB");

    [uuid(B6127C55-AC5F-4ba0-AFF6-7220C95EEF4D), dual, oleautomation, hidden, nonextensible]
    interface IExample2VTbl : IDispatch
    {
        [helpstring("Sets the test string.")]
        [id(1), propput] HRESULT Buffer([in] BSTR);
        [helpstring("Gets the test string.")]
        [id(1), propget] HRESULT Buffer([out, retval] BSTR *);
    };

    [uuid(520F4CFD-61C6-4eed-8004-C26D514D3D19), helpstring("IExample2 object."), appobject]
    coclass IExample2
    {
        [default] interface IExample2VTbl;
    }
}

