#
TOPDIR = ../..

#
include $(TOPDIR)/make.inc

#
SUBDIRS = dsplayer     \
          ddraw        \
          dsplayer     \

#
all:
	$(MAKEALL_SUBDIRS)
  
#
.PHONY : clean
clean :
	$(MAKECLEAN_SUBDIRS)

