#
TOPDIR = ../..
#
include $(TOPDIR)/make.inc

SUBDIRS = dlg_gdiplus      \
          win_gdiplus      \
          themometer       \
          button_gdiplus   \
          weather_gdiplus  \
          chart_gdiplus    \
          print_gdiplus    \
          curve_gdiplus    \
          contour_gdiplus  \
          gradient_gdiplus \
          colormap_gdiplus \

#
all:
	$(MAKEALL_SUBDIRS)

#
.PHONY : clean
clean :
	$(MAKECLEAN_SUBDIRS)
