#
TOPDIR = ../..
#
include $(TOPDIR)/make.inc

#
SUBDIRS = btree  \
          vector \
          stack  \
          algo   \
          sort   \
          pair   \
          string \
          mine   \
          prime  \
          graph  \
          search \
          list   \
          comparable \
          table  \
          queue  \
          recursion \
          functional \
          bitset    \
          set       \
          multiset  \
          multimap  \

#
all:
	$(MAKEALL_SUBDIRS)

.PHONY : clean
clean :
	$(MAKECLEAN_SUBDIRS)
