#
TOPDIR = ../..
#
include $(TOPDIR)/make.inc

SUBDIRS = dlg_gdiplus      \
          win_gdiplus      \
          themometer       \
          button_gdiplus   \
          weather_gdiplus  \
          chart_gdiplus    \

#
all:
	$(MAKEALL_SUBDIRS)

#
.PHONY : clean
clean :
	$(MAKECLEAN_SUBDIRS)
